language: node_js

node_js:
  - stable

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- -- version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  directory:
    - $HOME/.yarn/bin

install: yarn install

script: yarn workspace @magicspace/tslint-rules test
